apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kubehunterreports.aquasecurity.github.com
spec:
  group: aquasecurity.github.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
  scope: Cluster
  names:
    singular: kubehunterreport
    plural: kubehunterreports
    kind: KubeHunterReport
    listKind: KubeHunterReportList
    categories:
      - all
