apiVersion: v1
kind: ConfigMap
metadata:
  name: starboard
  labels:
    {{- include "starboard-operator.labels" . | nindent 4 }}
data:
  {{- if .Values.trivy.enabled }}
  vulnerabilityReports.scanner: "Trivy"
  configAuditReports.scanner: "Polaris"
  trivy.imageRef: "{{ .Values.trivy.imageRef }}"
  trivy.mode: "{{ .Values.trivy.mode }}"
  {{- if eq .Values.trivy.mode "ClientServer" }}
  trivy.serverURL: "{{ .Values.trivy.serverURL }}"
  {{- end }}
  trivy.httpProxy: "{{ .Values.trivy.httpProxy }}"
  trivy.httpsProxy: "{{ .Values.trivy.httpsProxy }}"
  trivy.noProxy: "{{ .Values.trivy.noProxy }}"
  trivy.severity: "{{ .Values.trivy.severity }}"
  {{- end }}
  {{- if .Values.kubeBench.enabled }}
  kube-bench.imageRef: "{{ .Values.kubeBench.imageRef }}"
  {{- end }}
  polaris.imageRef: "{{ .Values.polaris.imageRef }}"
  polaris.config.yaml: |
    {{- toYaml .Values.polaris.config | nindent 4 }}
  conftest.imageRef: openpolicyagent/conftest:v0.23.0
  kube-bench.imageRef: docker.io/aquasec/kube-bench:0.5.0
