---
apiVersion: v1
kind: ConfigMap
metadata:
  name: starboard
  labels:
    {{- include "starboard-operator.labels" . | nindent 4 }}
data:
  scanJob.tolerations: {{ .Values.starboard.scanJobTolerations | toJson | quote }}
  scanJob.annotations: {{ .Values.starboard.scanJobAnnotations | quote }}
  {{- if .Values.operator.vulnerabilityScannerEnabled }}
  vulnerabilityReports.scanner: {{ .Values.starboard.vulnerabilityReportsPlugin | quote }}
  {{- if eq .Values.starboard.vulnerabilityReportsPlugin "Trivy" }}
  trivy.imageRef: "{{ .Values.trivy.imageRef }}"
  trivy.mode: "{{ .Values.trivy.mode }}"
  {{- if eq .Values.trivy.mode "ClientServer" }}
  trivy.serverURL: "{{ .Values.trivy.serverURL }}"
  {{- end }}
  trivy.httpProxy: "{{ .Values.trivy.httpProxy }}"
  trivy.httpsProxy: "{{ .Values.trivy.httpsProxy }}"
  trivy.noProxy: "{{ .Values.trivy.noProxy }}"
  trivy.severity: "{{ .Values.trivy.severity }}"
  {{- end }}
  {{- end }}
  {{- if .Values.operator.kubernetesBenchmarkEnabled }}
  kube-bench.imageRef: "{{ .Values.kubeBench.imageRef }}"
  {{- end }}
  {{- if .Values.operator.configAuditScannerEnabled }}
  configAuditReports.scanner: {{ .Values.starboard.configAuditReportsPlugin | quote }}
  {{- end }}
{{- if eq .Values.starboard.configAuditReportsPlugin "Conftest" }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: starboard-conftest-config
  labels:
    {{- include "starboard-operator.labels" . | nindent 4 }}
data:
  conftest.imageRef: {{ .Values.conftest.imageRef | quote }}
{{- end }}
{{- if eq .Values.starboard.configAuditReportsPlugin "Polaris" }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: starboard-polaris-config
  labels:
    {{- include "starboard-operator.labels" . | nindent 4 }}
data:
  polaris.imageRef: "{{ .Values.polaris.imageRef }}"
  polaris.config.yaml: |
  {{- toYaml .Values.polaris.config | nindent 4 }}
{{- end }}
{{- if eq .Values.starboard.vulnerabilityReportsPlugin "Aqua" }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: starboard-aqua-config
  labels:
     {{- include "starboard-operator.labels" . | nindent 4 }}
data:
  aqua.imageRef: {{ required ".Values.aqua.imageRef is required!" .Values.aqua.imageRef | quote }}
  aqua.serverURL: {{ required ".Values.aqua.serverURL is required!" .Values.aqua.serverURL | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: starboard-aqua-config
  labels:
    {{- include "starboard-operator.labels" . | nindent 4 }}
data:
  aqua.username: {{ required ".Values.aqua.username is required!" .Values.aqua.username | b64enc | quote }}
  aqua.password: {{ required ".Values.aqua.password is required!" .Values.aqua.password | b64enc | quote }}
{{- end}}
