---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "starboard-operator.fullname" . }}
  labels:
    {{- include "starboard-operator.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      name: metrics
  selector:
    {{- include "starboard-operator.selectorLabels" . | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "starboard-operator.fullname" . }}
  labels:
    {{- include "starboard-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.operator.replicas }}
  selector:
    matchLabels:
      {{- include "starboard-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- . | toYaml | nindent 8 }}
        {{- end }}
      labels:
        {{- include "starboard-operator.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: "{{ .Chart.Name }}"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          env:
            - name: OPERATOR_NAMESPACE
              value: {{ .Release.Namespace | quote }}
            - name: OPERATOR_TARGET_NAMESPACES
              value: {{ tpl .Values.targetNamespaces . | quote }}
            - name: OPERATOR_SERVICE_ACCOUNT
              value: {{ include "starboard-operator.serviceAccountName" . }}
            {{- if gt (int .Values.operator.replicas) 1 }}
            - name: OPERATOR_LEADER_ELECTION_ENABLED
              value: "true"
            {{- end }}
            {{- if gt (int .Values.operator.replicas) 1 }}
            - name: OPERATOR_LEADER_ELECTION_ID
              value: {{ .Values.operator.leaderElectionId | quote }}
            {{- end }}
            - name: OPERATOR_METRICS_BIND_ADDRESS
              value: ":8080"
            - name: OPERATOR_HEALTH_PROBE_BIND_ADDRESS
              value: ":9090"
            - name: OPERATOR_LOG_DEV_MODE
              value: {{ .Values.operator.logDevMode | quote }}
            - name: OPERATOR_CIS_KUBERNETES_BENCHMARK_ENABLED
              value: {{ .Values.operator.kubernetesBenchmarkEnabled | quote }}
            - name: OPERATOR_VULNERABILITY_SCANNER_ENABLED
              value: {{ .Values.operator.vulnerabilityScannerEnabled | quote }}
            - name: OPERATOR_CONFIG_AUDIT_SCANNER_ENABLED
              value: {{ .Values.operator.configAuditScannerEnabled | quote }}
            - name: OPERATOR_BATCH_DELETE_LIMIT
              value: {{ .Values.operator.batchDeleteLimit | quote }}
            - name: OPERATOR_BATCH_DELETE_DELAY
              value: {{ .Values.operator.batchDeleteDelay | quote }}
          ports:
            # metrics port is exposed by the k8s Service and by default also
            # have annotations which will help prometheus as a target for
            # scraping of metrics
            - name: metrics
              containerPort: 8080
            # probes port is not exposed by the k8s Service and used directly by
            # kubelet for the readinessProbe and livenessProbe
            - name: probes
              containerPort: 9090
          readinessProbe:
            httpGet:
              path: /readyz/
              port: probes
            initialDelaySeconds: 0
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthz/
              port: probes
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 10
          resources:
            {{- .Values.resources | toYaml | nindent 12 }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          {{- with .Values.image.pullPolicy }}
          imagePullPolicy: {{ . }}
          {{- end }}
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "starboard-operator.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
