apiVersion: v1
kind: Service
metadata:
  name: {{ include "starboard-operator.fullname" . }}
  labels:
    {{- include "starboard-operator.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- .Values. | toYaml | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: metrics
      name: metrics
  selector:
    {{- include "starboard-operator.selectorLabels" . | nindent 4 }}
