run:
  timeout: 5m
linters:
  enable:
    - asciicheck
    - errcheck
    - errorlint
    - gci
    - gofmt
    - gofumpt
    - gosimple
    - govet
    - misspell
  disable:
    - ineffassign
    - staticcheck
