release:
  draft: false
  prerelease: auto
env:
  - GO111MODULE=on
  - CGO_ENABLED=0
before:
  hooks:
    - go mod download
builds:
  - id: starboard
    main: ./cmd/starboard/main.go
    binary: starboard
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "7"
    ignore:
      - goos: darwin
        goarch: s390x
      - goos: windows
        goarch: s390x
  - id: starboard-operator
    main: ./cmd/starboard-operator/main.go
    binary: starboard-operator
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
      - s390x
      - ppc64le
    goarm:
      - "7"
  - id: starboard-operator-fips
    main: ./cmd/starboard-operator/main.go
    binary: starboard-operator-fips
    flags:
      - -tags=fipsonly
    env:
      - GOEXPERIMENT=boringcrypto
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
      - s390x
      - ppc64le
    goarm:
      - "7"
  - id: starboard-scanner-aqua
    main: ./cmd/scanner-aqua/main.go
    binary: starboard-scanner-aqua
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "7"
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "arm" }}ARM
      {{- else if eq .Arch "arm64" }}ARM64
      {{- else }}{{ .Arch }}{{ end }}
    builds:
      - starboard
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .FullCommit }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs'
      - '^test'
      - '^release'
dockers:
  - image_templates:
      - "docker.io/aquasec/private-test:{{ .Version }}-amd64"
      - "{{ .Env.AQUSEC_ACR_REGISTRY_NAME }}/lihitest-starboard:{{ .Version }}-amd64"
    use: buildx
    goos: linux
    dockerfile: build/starboard/Dockerfile
    goarch: amd64
    ids:
      - starboard
    build_flag_templates:
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.description=Command line interface for Starboard"
      - "--label=org.opencontainers.image.vendor=Aqua Security"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.source=https://github.com/aquasecurity/starboard"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.documentation=https://aquasecurity.github.io/starboard/v{{ .Version }}/"
      - "--platform=linux/amd64"

docker_manifests:
  - name_template: "aquasec/private-test:{{ .Version }}"
    image_templates:
      - "aquasec/private-test:{{ .Version }}-amd64"

  # Aqua container registry
  - name_template: "{{ .Env.AQUSEC_ACR_REGISTRY_NAME }}/lihitest-starboard:{{ .Version }}"
    image_templates:
      - "{{ .Env.AQUSEC_ACR_REGISTRY_NAME }}/lihitest-starboard:{{ .Version }}-amd64"