release:
  draft: true
  prerelease: auto

env:
  - GO111MODULE=on
  - CGO_ENABLED=0

checksum:
  name_template: "checksums.txt"

builds:
  - id: starboard
    main: ./cmd/starboard/main.go
    binary: starboard
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "7"
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "arm" }}ARM
      {{- else if eq .Arch "arm64" }}ARM64
      {{- else }}{{ .Arch }}{{ end }}
    builds:
      - starboard
    format_overrides:
      - goos: windows
        format: zip
dockers:
  - image_templates:
      - "aquasec.azurecr.io/starboard-lihitest:{{ .Version }}-amd64"
    use: buildx
    goos: linux
    dockerfile: build/starboard/Dockerfile
    goarch: amd64
    ids:
      - starboard
    build_flag_templates:
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.description=Command line interface for Starboard"
      - "--label=org.opencontainers.image.vendor=Aqua Security"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.source=https://github.com/aquasecurity/starboard"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.documentation=https://aquasecurity.github.io/starboard/v{{ .Version }}/"
      - "--platform=linux/amd64"

docker_manifests:
  - name_template: "aquasec/starboard:{{ .Version }}"
    image_templates:
      - "aquasec/starboard:{{ .Version }}-amd64"
