env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
  - id: starboard
    main: ./cmd/starboard/main.go
    binary: starboard
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
  - id: starboard-macos
    main: ./cmd/starboard/main.go
    binary: starboard
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .FullCommit }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs'
      - '^test'
      - '^release'
signs:
  - signature: "starboard.dmg"
    id: dmg
    ids:
      - starboard-macos # here we filter the macos only build id
    cmd: gon
    args:
      - gon.json
    artifacts: all
  - signature: "starboard.zip"
    id: zip
    ids:
      - starboard-macos # here we filter the macos only build id
    cmd: gon
    args:
      - gon.json
    artifacts: all
