site_name: Starboard
site_url: https://aquasecurity.github.io/starboard/
site_description: Kubernetes-native security toolkit
docs_dir: docs/
repo_name: GitHub
repo_url: https://github.com/aquasecurity/starboard
edit_uri: ""

nav:
  - Introduction: index.md
  - Starboard CLI:
      - Overview: cli/index.md
      - Installation:
          - Binary Release: cli/installation/binary-release.md
          - Krew: cli/installation/krew.md
          - Docker: cli/installation/docker.md
          - From Source Code: cli/installation/source-code.md
      - Getting Started: cli/getting-started.md
  - Starboard Operator:
      - Overview: operator/index.md
      - Installation:
          - kubectl: operator/installation/kubectl.md
          - Helm: operator/installation/helm.md
          - Operator Lifecycle Manager: operator/installation/olm.md
      - Getting Started: operator/getting-started.md
      - Configuration: operator/configuration.md
  - Configuration: configuration.md
  - Integrations: integrations.md
  - Custom Resource Definitions: crds.md
  - Frequently Asked Questions: faq.md
  - Troubleshooting: troubleshooting.md

theme:
  name: material
  highlightjs: true
  language: 'en'
