apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: kubehunterreports.aquasecurity.github.io
  labels:
    app.kubernetes.io/managed-by: starboard
spec:
  group: aquasecurity.github.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      additionalPrinterColumns:
        - jsonPath: ".report.scanner.name"
          name: "Scanner"
          type: "string"
        - jsonPath: ".metadata.creationTimestamp"
          name: "Age"
          type: "date"
        - jsonPath: ".report.summary.highCount"
          name: "High"
          type: "integer"
          priority: 1
        - jsonPath: ".report.summary.mediumCount"
          name: "Medium"
          type: "integer"
          priority: 1
        - jsonPath: ".report.summary.lowCount"
          name: "Low"
          type: "integer"
          priority: 1
      schema:
        openAPIV3Schema:
          x-kubernetes-preserve-unknown-fields: true
          type: "object"
  scope: Cluster
  names:
    singular: kubehunterreport
    plural: kubehunterreports
    kind: KubeHunterReport
    listKind: KubeHunterReportList
    categories:
      - all
    shortNames:
      - kubehunter
