name: build
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Vendor Go modules
        run: go mod vendor
      - name: Verify generated code
        run: GOPATH="$(go env GOPATH)" ./hack/verify-codegen.sh
