---
# This workflow is triggered whenever we release a new version of Starboard
# by creating an annotated Git tag and pushing it to the upstream Git repository.
#
#    git tag -a v0.0.1 -m 'Release v0.0.1'
#    git push upstream v0.0.1
name: Release-Test-Lihi
on:
  push:
    branches:
      - lihitest-release-*
env:
  GO_VERSION: "1.23.1"
  KIND_VERSION: "v0.11.1"
  KIND_IMAGE: "kindest/node:v1.21.1@sha256:69860bda5563ac81e3c0057d654b5253219618a22ec3a346306239bba8cfa1a6"
jobs:
  release:
    name: Release-Test-Lihi
    runs-on: ubuntu-20.04
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    steps:
      - name: login to azure acr - Lihitest2
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.AQUSEC_ACR_REGISTRY_NAME }}
          username: ${{ secrets.AQUASEC_ACR_USERNAME }}
          password: ${{ secrets.AQUASEC_ACR_PASSWORD }}

      - name: Cleanup Docker and KIND resources (Pre-Release)
        run: |
          docker system prune -a --force
          docker volume prune --force
      - name: Check disk usage (Pre-Release)
        run: df -h
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

#      - name: login to azure acr - Lihitest2
#        uses: azure/docker-login@v2
#        with:
#          login-server: ${{ env.AQUSEC_ACR_REGISTRY_NAME }}
#          username: ${{ env.AQUASEC_ACR_USERNAME }}
#          password: ${{ env.AQUASEC_ACR_PASSWORD }}

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Login to docker.io registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Release
        uses: goreleaser/goreleaser-action@v3
        with:
          version: v1.7.0
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   #   - name: Update new version for plugin 'starboard' in krew-index
   #     uses: rajatjindal/krew-release-bot@v0.0.43

      - name: Cleanup Docker and KIND resources
        run: |
          docker system prune -a --force
          docker volume prune --force
      - name: Check disk usage
        run: df -h
