name: Release
on:
  push:
    tags:
      - "v*"
jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    steps:
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run unit tests
        run: make unit-tests
      - name: Setup Kubernetes cluster (KIND)
        uses: engineerd/setup-kind@v0.4.0
        with:
          version: v0.9.0
          image: kindest/node:v1.18.8@sha256:f4bcc97a0ad6e7abaf3f643d890add7efe6ee4ab90baeb374b4f41a4c95567eb
      - name: Test connection to Kubernetes cluster
        run: |
          kubectl cluster-info
      - name: Run integration tests
        run: |
          make integration-tests
        env:
          KUBECONFIG: /home/runner/.kube/config
          STARBOARD_CLI_LOG_LEVEL: "0"
      - name: Log in to docker.io registry
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login docker.io --username ${{ secrets.DOCKERHUB_USER }} --password-stdin
      - name: Release
        uses: goreleaser/goreleaser-action@v2
        with:
          version: v0.145.0
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Log out from docker.io registry
        if: ${{ always() }}
        run: |
          docker logout docker.io
      - name: Update new version for plugin 'starboard' in krew-index
        uses: rajatjindal/krew-release-bot@v0.0.38
