name: Release
on:
  push:
    tags:
      - "v*"
jobs:
  release:
    name: Release
    runs-on: macos-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run unit tests
        run: make unit-tests

      - name: Import Code-Signing Certificates
        uses: Apple-Actions/import-codesign-certs@v1
        with:
          # The certificates in a PKCS12 file encoded as a base64 string created with "openssl base64 -in cert.p12 -out cert-base64.txt"
          p12-file-base64: ${{ secrets.APPLE_DEVELOPER_CERTIFICATE_P12_BASE64 }}
          # The password used to import the PKCS12 file.
          p12-password: ${{ secrets.APPLE_DEVELOPER_CERTIFICATE_PASSWORD }}

      - name: Install gon
        run: |
          brew tap mitchellh/gon
          brew install mitchellh/gon/gon

      - name: Create gon config file
        run: |
          echo ${{ secrets.GON_DMG_CONFIG_BASE64 }} | base64 --decode > gon.json

      - name: Release
        uses: goreleaser/goreleaser-action@v2
        with:
          version: v0.138.0
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update new version for plugin 'starboard' in krew-index
        uses: rajatjindal/krew-release-bot@v0.0.38
